version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: dan/reverseproxy
  backend_user:
    build:
      context: ../../udacity-c3-restapi-users
    image: dan/udacity-restapi-users
  backend_feed:
    build:
      context: ../../udacity-c3-restapi-feed  
    image: dan/udacity-restapi-feed
  frontend:
    build:
      context: ../../udacity-c3-frontend  
    image: dan/udacity-frontend:local