version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: danman28/reverseproxy
  backend_user:
    build:
      context: ../../udacity-c3-restapi-users
    image: danman28/udacity-restapi-users
  backend_feed:
    build:
      context: ../../udacity-c3-restapi-feed  
    image: danman28/udacity-restapi-feed
  backend_filter:
    build:
      context: ../../udagram-filter
    image: danman28/udagram-filter  
  frontend:
    build:
      context: ../../udacity-c3-frontend  
    image: danman28/udacity-frontend:local
  